main: beansplusplus.beansgameplugin.BeansGamePlugin
name: BeansGamePlugin
version: 1
api-version: 1.19
description: >
  Beans gamemode wrapper
commands:
  config:
    description: >
      Configure game settings
  start:
    description: >
      Start game
  stop:
    description: >
      Stop game
  reset:
    description: >
      Reset game
  pause:
    description: >
      Force pause the game
  continue:
    description: >
      Unpause a paused game
    aliases:
      - unpause
  rules:
    description: >
      Show rules of the game
