main: beansplusplus.gameconfig.GameConfigPlugin
name: GameConfigPlugin
version: 1
api-version: 1.19
description: >
  Create configs from
commands:
  config:
    description: >
      Configure game settings