name: Build and Publish
on:
  push:
    branches:
      - main
jobs:
  make-jar:
    name: Build and Upload jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 16

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: gradle jar

      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: build/libs  # This folder should contain only the Jar file
          container_name: www
          account_name: saggyresourcepack
          sas_token: ${{ secrets.StorageSAS }}
          overwrite: 'true'
  publish:
    name: Publish to github packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 16
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}